# Generated by Django 5.1.1 on 2024-10-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowings", "0007_alter_borrowing_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("G", "PENDING"), ("D", "PAID")],
                        default="G",
                        max_length=1,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("P", "PAYMENT"), ("F", "FINE")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("session_url", models.URLField()),
                ("session_id", models.CharField(max_length=120)),
                ("money", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowings.borrowing",
                    ),
                ),
            ],
        ),
    ]
