# Generated by Django 5.1.1 on 2024-10-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_alter_payment_session_id_alter_payment_session_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("G", "PENDING"), ("D", "PAID"), ("E", "EXPIRED")],
                default="G",
                max_length=1,
            ),
        ),
    ]
