# Generated by Django 5.1.1 on 2024-10-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_inventory"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("title", "author", "cover")},
        ),
    ]
