# Generated by Django 5.1.1 on 2024-09-30 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_return_date__lte", datetime.date(2024, 9, 30)),
                    ("actual_return_date__isnull", True),
                    _connector="OR",
                ),
                name="actual return date must be before or equal to today's date or null",
            ),
        ),
    ]
