# Generated by Django 5.1.1 on 2024-10-02 08:02

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_unique_together"),
        (
            "borrowings",
            "0004_remove_borrowing_actual_borrow_date_must_be_equal_to_today_s_date_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="actual return date must be before or equal to today's date or null",
        ),
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="actual borrow date must be equal to today's date",
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_return_date__lte", datetime.date(2024, 10, 2)),
                    ("actual_return_date__isnull", True),
                    _connector="OR",
                ),
                name="actual return date must be before or equal to today's date or null",
            ),
        ),
    ]
