# Generated by Django 5.1.1 on 2024-10-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "borrowings",
            "0005_remove_borrowing_actual_return_date_must_be_before_or_equal_to_today_s_date_or_null_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="actual return date must be before or equal to today's date or null",
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
