# Generated by Django 5.1.1 on 2024-10-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "borrowings",
            "0006_remove_borrowing_actual_return_date_must_be_before_or_equal_to_today_s_date_or_null_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={
                "ordering": [
                    "borrow_date",
                    "expected_return_date",
                    "actual_return_date",
                ],
                "verbose_name_plural": "borrowings",
            },
        ),
    ]
