# Generated by Django 5.1.1 on 2024-10-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0007_alter_borrowing_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="actual return date must be after or equal to the borrow date or null",
        ),
    ]
